Evidence/Controllers/ActionsController.cs
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Evidence.Data.Interfaces;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Evidence.Models;
using Evidence.Models.ViewModels;
using Action = Evidence.Models.Action;

namespace Evidence.Controllers
{
    public class ActionsController : Controller
    {
        private readonly EvidenceContext _ctx;
        private readonly IActionRepository _actionRepository;

        public ActionsController(EvidenceContext ctx, IActionRepository actionRepository)
        {
            _ctx = ctx;
            _actionRepository = actionRepository;
        }

        // GET: Actions ++
        public async Task<IActionResult> Index()
        {
            return View(await _actionRepository.GetActions());
        }

        // GET: Actions/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _actionRepository.GetAction((int)id);

            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // GET: Actions/Create
        // V pripade s kontrolovanim hodin bylo by vhodnejsi napsat JavaScript 
        public IActionResult Create(string? message)
        {
            var vm = new ActionAddEditViewModel {Employees = _ctx.Employees.ToList(), Projects = _ctx.Projects.ToList(), ActionDate = DateTime.Today };

            if (!string.IsNullOrEmpty(message))
                ViewData["message"] = message;

            return View(vm);
        }

        //POST: Actions/Create/Model
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind]ActionAddEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (await _actionRepository.AddAction(vm))
                {
                    return RedirectToAction("Index");
                }

                return RedirectToAction("Create", new {message = "Překročen povolený počet hodin pro tento den" });
            }

            return RedirectToAction("Index");
        }

        // GET: Actions/Edit/5
        public async Task<IActionResult> Edit(int? id, string? message)
        {
            if (id == null)
            {
                return NotFound();
            }

            if (!string.IsNullOrEmpty(message))
                ViewData["message"] = message;

            var getAction = await _actionRepository.GetAction((int)id);

            var vm = new ActionAddEditViewModel 
            {   
                Employees = _ctx.Employees.ToList(),
                Projects = _ctx.Projects.ToList(),
                Cost = getAction.Cost,
                SpentTime = getAction.SpentTime,
                SelectedEmployee = getAction.EmployeeNavigation.Id,
                SelectedProject = getAction.ProjectNavigation.Id,
                ActionDate = getAction.ActionDate
            };

            return View(vm);
        }

        // POST: Actions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([Bind]ActionAddEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                if (await _actionRepository.EditAction(vm))
                {
                    return RedirectToAction("Edit", new {vm.Id });
                }

                return RedirectToAction("Edit", new {vm.Id, message = "Překročen povolený počet hodin pro tento den" });
            }
            return RedirectToAction("Index");
        }

        // GET: Actions/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var action = await _actionRepository.GetAction((int)id);

            if (action == null)
            {
                return NotFound();
            }

            return View(action);
        }

        // POST: Actions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await _actionRepository.DeleteAction(id);
            return RedirectToAction("Index");
        }

        private bool ActionExists(int id)
        {
            return _ctx.Actions.Any(e => e.Id == id);
        }
    }
}

Evidence/Controllers/EmployeeController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Evidence.Data;
using Evidence.Data.Interfaces;
using Evidence.Models;
using Evidence.Models.ViewModels;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace Evidence.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly EvidenceContext _ctx;
        private readonly IEmpolyeeRepository _repository;
        private readonly IPositionRepository _positionRepository;

        public EmployeeController(EvidenceContext ctx, IEmpolyeeRepository employeeRepository, IPositionRepository positionRepository)
        {
            _ctx = ctx;
            _repository = employeeRepository;
            _positionRepository = positionRepository;
        }

        // GET: ZamestnanceController
        public ActionResult Index()
        {
            return View(_repository.GetEmployees());
        }
        
        // GET: ZamestnanceController/Create
        public async Task<ActionResult> Create()
        {
            var positions = await _positionRepository.GetPositions();
            var vm = new EmployeeAddViewModel { Positions = positions.ToList() };

            return View(vm);
        }

        // POST: ZamestnanceController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(EmployeeAddViewModel vm)
        {
            if(ModelState.IsValid){
                _repository.CreateEmployee(vm);
                return RedirectToAction("Index");
            }
            return View();
        }

    }
}

Evidence/Controllers/ProjectController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Evidence.Data;
using Evidence.Models;
using Microsoft.EntityFrameworkCore;

namespace Evidence.Controllers
{
    public class ProjectController : Controller
    {
        private readonly EvidenceContext _ctx;
        private readonly IProjectRepository _projectRepository;

        public ProjectController(EvidenceContext ctx, IProjectRepository projectRepository)
        {
            _ctx = ctx;
            _projectRepository = projectRepository;
        }

        public async Task<IActionResult> Index()
        {
            IEnumerable<Project> projects = await _projectRepository.GetProjects();
            return View(projects);
        }

        //GET
        public IActionResult Create()
        {
            return View();
        }

        //POST
        [HttpPost]
        public async Task<IActionResult> Create(Project project)
        {
            if(project == null)
                return RedirectToAction("Index");

            await _projectRepository.AddProject(project);

            return RedirectToAction("Index");
        }
    }
}

Evidence/Controllers/ReportController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Evidence.Data.Interfaces;
using Evidence.Models;
using Evidence.Models.ViewModels;

namespace Evidence.Controllers
{
    public class ReportController : Controller
    {
        private readonly EvidenceContext _ctx;
        private readonly IReportRepository _reportRepository;

        public ReportController(EvidenceContext ctx, IReportRepository reportRepository)
        {
            _ctx = ctx;
            _reportRepository = reportRepository;
        }

        //GET
        public async Task<IActionResult> Index()
        {
            var result = await _reportRepository.GetReport();
            return View(result);
        }

        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Index([Bind] DateTime? dateFrom, DateTime? dateTo)
        {
            ReportsViewModel vm;

            if (dateFrom == null || dateTo == null)
                vm = await _reportRepository.GetReport();

            vm = await _reportRepository.GetReportByDate(dateFrom, dateTo);

            return View(vm);
        }
    }
}

Evidence/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Evidence</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Report" asp-action="Index">Report</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Actions" asp-action="Index">Činností</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Project" asp-action="Index">Projekty</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Zaměstnancé</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Position" asp-action="Index">Pozice</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
           Evidence - Homework Profinit - Ferenc Doča</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>